import { Activity, HeartPulse, Leaf, Server, ShieldCheck, Thermometer } from 'lucide-react'

const principles = [{ icon: HeartPulse, title: 'People first', text: 'Comfort scores turn environmental readings into decisions that support health and dignity.' }, { icon: Leaf, title: 'Local by design', text: 'The model is shaped for area-specific shelters, materials, weather, and daily use.' }, { icon: ShieldCheck, title: 'Actionable output', text: 'Every analysis ends with a simple risk status and practical next steps.' }]
const projectDetails = [
	['Project ID', 'SIH26051'],
	['Objective', 'Model and communicate thermal comfort for area-specific shelters.'],
	['Comfort concept', 'A combined view of temperature, humidity, air movement, radiant heat, activity, and clothing.'],
	['Environmental inputs', 'Air temperature, relative humidity, air velocity, and mean radiant temperature.'],
]

export default function AboutPage() { return <div className="space-y-7"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-600">About the project</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">A calmer way to understand shelter comfort.</h1><p className="mt-3 text-sm leading-6 text-slate-500">ThermalSense is a Smart India Hackathon 2026 concept for making thermal modelling more useful at the scale where people experience it: their local shelter.</p></div><div className="grid gap-3 sm:grid-cols-2">{projectDetails.map(([label, value]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/40"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-400">{label}</p><p className="mt-2 text-sm leading-6 text-slate-700">{value}</p></article>)}</div><div className="grid gap-4 md:grid-cols-3">{principles.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/40"><span className="grid h-10 w-10 place-items-center rounded-xl bg-orange-50 text-orange-600"><Icon size={19} /></span><h2 className="mt-5 text-sm font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></article>)}</div><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/40"><div className="flex items-center gap-2"><Activity size={18} className="text-orange-500" /><h2 className="text-sm font-bold text-slate-900">How the system works</h2></div><div className="mt-5 grid gap-4 md:grid-cols-3"><Step icon={Thermometer} number="01" title="Collect" text="Capture shelter and occupant conditions in the analysis form." /><Step icon={Activity} number="02" title="Model" text="Calculate a representative comfort index and heat-risk category." /><Step icon={Server} number="03" title="Act" text="Use recommendations to guide ventilation, shade, hydration, or material changes." /></div><p className="mt-5 border-t border-slate-100 pt-4 text-xs leading-5 text-slate-500">The current demonstration uses mock data and a local service layer. A future backend API can replace the mock functions in <strong>src/services/api.js</strong> without changing the page components.</p></section></div> }

function Step({ icon: Icon, number, title, text }) { return <div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-950 text-orange-300"><Icon size={16} /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-orange-600">{number}</p><h3 className="mt-1 text-sm font-bold text-slate-800">{title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div> }
